from .author import GoodreadsAuthor as Author
from .book import GoodreadsBook as Book
from .client import GoodreadsClient as Client
from .comment import GoodreadsComment as Comment
from .event import GoodreadsEvent as Event
from .group import GoodreadsGroup as Group
from .owned_book import GoodreadsOwnedBook as OwnedBook
from .review import GoodreadsReview as Review
from .user import GoodreadsUser as User
from .user_status import GoodreadsUserStatus as UserStatus
